#43 Added cargo-process-new global keybind
rakanalh/emacs-bootstrap pull request #44
Opened 2019-10-16 22:44 UTC by Tiv0w

2019-10-16 23:09 UTC, Tiv0w commented
relative to #43

2019-11-07 17:53 UTC, avelino requested changes
if add cargo-minor-mode to your rust-mode-hook working

```elisp
:init
(add-hook 'rust-mode-hook 'cargo-minor-mode)
```

2019-11-07 23:28 UTC, Tiv0w commented
Fixed. Added some hooks with the use-package `:hook` keyword, so the loading is deferred.

2019-11-08 00:55 UTC, avelino approved these changes

2019-11-08 00:55 UTC, merged